on:
  push:
    paths: 
      - 'test-versioning/**'
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      # caching NPM dependencies
      # https://github.com/actions/cache/blob/master/examples.md#node---npm
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare variables
        id: vars
        run: |
          cd test-versioning
          npm version minor
          DOCKER_IMAGE=dhananjay12/angular-test-versioning
          DOCKER_TAG=$(node -pe "require('./package.json').version")
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=tag::${DOCKER_TAG}

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Release Image
        run: |
          cd test-versioning
          npm i
          npm run build:prod
          docker build . --file Dockerfile --tag ${{steps.vars.outputs.image}}:${{steps.vars.outputs.tag}}
          docker push ${{steps.vars.outputs.image}}:${{steps.vars.outputs.tag}}

      - name: Push tag to GitHub
        run: |
          git config --global user.name 'Auto Releaser'
          git config --global user.email 'autoReleaser@dhananjay12.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Release v${{steps.vars.outputs.tag}}"
          git push
          git tag v${{steps.vars.outputs.tag}}
          git push --tags
